#!/usr/bin/env bash
# build <repo-id> <build-id> <build-pack>

### Environment setup

set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # current direct of script

source "$DIR/lib/output.sh"

ROOT_BUILD_DIR="$DIR/../.tmp"

### Inputs

REPO_ID=${1:-}
BUILD_ID=${2:-}
BUILD_PACK=${3:-}

CACHE_DIR="$ROOT_BUILD_DIR/.cache/$REPO_ID"
BUILD_DIR="$ROOT_BUILD_DIR/$BUILD_ID"
ENV_DIR="$ROOT_BUILD_DIR/.env/$REPO_ID"

bash "$DIR/../buildpacks/$BUILD_PACK/bin/compile" "$BUILD_DIR" "$CACHE_DIR" "$ENV_DIR"