#!/usr/bin/env bash
# compile <repo-id> <build-id>

### Environment setup

set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # current direct of script

source "$DIR/lib/output.sh"

ROOT_BUILD_DIR="$DIR/../.tmp"

### Variables

REPO_ID=${1:-}
BUILD_ID=${2:-}

### Script

header "Compressing"

tar -czf "$ROOT_BUILD_DIR/$BUILD_ID.tar.gz" --directory="$ROOT_BUILD_DIR/$BUILD_ID" .